### ISSUE TITLE
Meldungen Import: Gemeinschaften nicht übernommen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/seltec#10]
Veranstaltung: https://ladv.de/ausschreibung/detail/16898
T&F Version: 3.1.2048

Problem: Athleten die für eine LG Starten werden nur mit ihrem Stammverein angezeigt.

**Comment by DocFrag** [comment]
In 3.1.0.2050 aufgrund der Verwendung von XML 0.7 behoben
