### ISSUE TITLE
Upload XML mit DMM funktioniert nicht

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/seltec#12]
Veranstaltung: https://ladv.de/ausschreibung/detail/18341
und
Veranstaltung: https://ladv.de/veranstaltung/detail/15572
Track and Field 3.1.0.1923

**Comment by DocFrag** [comment]
Fehler wurde bereits in der internen Revision #3.1.0.2085 behoben, und wird mit dem nächsten Update ausgerollt. Endgültige Versionsnummer trage ich gerne noch nach
