### ISSUE TITLE
falscher Disziplincode für 300m Hürden

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/seltec#13]
Veranstaltung: https://ladv.de/ergebnisse/42398
Track and Field Version 3.1.0.2050

Problem: für 300m Hürden wird der falsche Disziplincode verwendet. 
Verwendet wird `H30`
Korrekt ist `H300`

Siehe Liste der Disziplincodes: https://ladv.de/entwickler/disziplinen

**Comment by DocFrag** [comment]
In interner Revision 3.1.0.2173 behoben, wird mit dem nächsten update ausgegerollt.
Der Code war für den Bewerb unabsichtlich beim Mapping doppelt vergeben
