### ISSUE TITLE
ungültige Werte für Attribut "county" in Element "club"

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/seltec#5]
Veranstaltung: https://ladv.de/veranstaltung/detail/14526

Tlw. enthalten Ergebnisdaten XMLs ungültige Werte für Attribut "county" im Element "club"
Zulässige Werte: maximal 3 Zeichen. Konstanten nach IOC Ländercodes - siehe Anhang 4 in Ergebnisdaten Dokumentation.

Beispiel:
```
<club country="NIEDERLNDE" id="..." type="CLUB" name="Achilles top Kerkrade" number="0" />
<club country="    " id="..." type="CLUB" name="VSV Rössing" number="0" />
<club country="NUEDERLANDE" id="..." type="CLUB" name="Atletiek Helden" number="0" />
```

**Comment by DocFrag** [comment]
Version 3.1.0.2050 verpflichtet den Nutzer nun zur Eingabe es korrekten Landes für einen Athleten und für Vereine. Entsprechend sollte dieses Problem damit nicht mehr auftreten.
