### ISSUE TITLE
ungültige Individual Referenz

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/seltec#7]
Veranstaltung: https://ladv.de/veranstaltung/detail/15188
Ergebnisdatendatei per Email (D. Wagner durch Veranstalter / 18.05.2018)

XML Fragment:
```xml
<combinedevent athlete="a14a17289-cccc-42ef-8330-82d10c701b0d" id="me5125dad-5b4f-4d6c-a69d-0ba9b79c4858" noncompetitive="false" place="0" result="a">
  <individualreference ref="i09f9ca89-d389-4280-8dc9-9bebe809c371" />
  <individualreference ref="i833a1ad5-1cc1-4bb0-96d2-ad317868c9f3" />
  <individualreference ref="i2fa0b7a9-ede7-4df1-a53a-559516578312" />
  <individualreference ref="ia59dd82e-14f5-4146-9df8-d8926d908414" /> <--- ungültige Referenz
  <individualreference ref="id258774f-29c9-47d6-9e3e-42552008b2e1" />
</combinedevent>
```

Problem: innerhalb eines Mehrkampfes wird eine Einzelleistung referenziert. Die Einzelleistung ist in der Datei nicht vorhanden. 

XML Datei wurde vom LADV Team händisch korrigiert. Es wurden drei Mehrämpfe ohne Leistung gelöscht die ungültige Referenzen enthalten. Veranstalter um Zusendung von Wettkampfdatenbank gebeten.

**Comment by DocFrag** [comment]
Fehler wurde in der internen Revision #3.1.0.2086 behoben und mit dem nächsten Update ausgerollt.
Endgültige Versionsnummer trage ich hier gerne dann nach
