### ISSUE TITLE
falsche Altersklassencodes

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/seltec#9]
Veranstaltung:
https://ladv.de/veranstaltung/detail/15276/Sparkassen-Kinder-und-Jugendspiele-Torgau.htm
XML Datei per Email. 

Problem: Altersklassencodes entsprechen nicht der Dokumentation

Beispiel:
```xml
<round ageclass="W9 " ...>
```
Weitere betroffene Altersklassen: `W08 `, `M08 `, `M09 ` 

Korrekt (kein Leerzeichen):
```xml
<round ageclass="W9" ...>
```

**Comment by mschunk** [comment]
Weitere Veranstaltung mit falschen Altersklassencodes:
https://ladv.de/veranstaltung/detail/15269
Xml Datei per Email. Veranstalter um Datenbank gebeten.

Problem: Altersklassencodes entsprechen nicht der Dokumentation. Hier Teamaltersklassen.

Beispiel:
```xml
<round ageclass="XU10" ...
```

Korrekt:
```xml
<round ageclass="TU10" ...
```

Dokumentation LADV Altersklassencodes:
https://ladv.de/entwickler/altersklassen

**Comment by mschunk** [comment]
Weitere Veranstaltung mit falschen Altersklassencodes:
https://ladv.de/veranstaltung/detail/15417
XML Datei händisch repariert:
`WU10` -> `WKU10`
`MU10` -> `MKU10`
T&F Version: 3.1.0.1923

**Comment by DocFrag** [comment]
Version 3.1.0.2050 hat nun eine Klassen-Mapping Tabelle.
Alles was halbwegs nach einem Standard aussieht, sollte dort vorhanden sein.

Alles was nicht Standard ist wir dem User nun als nicht-exportierbar gemeldet und beim Export übersprungen
Aber das meiste sollte mit dem Update somit gelöst/behoben sein

**Comment by DocFrag** [comment]
Wie geschrieben prüft Version 3.1.0.2050 anhand einer Mapping-Tabelle die Klassencodes. Dieser Issue kann daher geschlossen werden. Danke!

**Comment by mschunk** [comment]
Wie genau muss ich mir das mit der Mapping Tabelle vorstellen?

Das LADV Ergebnisdatenformat unterstützt derzeit keine "selbst definierten Altersklassen". Diese können damit derzeit nicht ausgegeben werden. Eine Andere Möglichkeit als Leistungen aus diesen Altersklassen beim XML export zu Unterdrücken sehe ich derzeit nicht. Das Leistungen entfernt werden sollte dem Anwender beim Export angezeigt werden, inkl. der Optionen die er hat: Standardaltersklasse verwenden oder Daten fehlen in der XML.

Gleichzeitig sollte bei Standardaltersklassen immer der Korrekte Disziplincode verwendet werden (siehe Problemmeldung + 1 Kommentar). Hier ging es um Kinderleichathletik Team Altersklasse und Kinder U10 (das sind Standaltersklassen)! 

Um "selbst definierte Altersklassen" in einer zukünftigen Version des LADV Ergebnisdaten Formates zu unterstützen, habe ich hier ein issue erstellt:
https://github.com/leichtathletik/ladv-datenformate/issues/3

**Comment by DocFrag** [comment]
Wir bieten dem User Standard-Klassen mit entsprechendem "Standard"-Code an.
Wenn der Benutzer jedoch etwas anders nutzen möchte, steht ihm das frei, selbst wenn es für den Fall eine Standard-Klasse gäbe.
Die neue Mapping-Tabelle führt zusätzlich nun auch ältere bekannte Codes, und wandelt diese dann beim Export zu LADV um z.b. SD -> MKU10
Damit können Nutzer ihre bekannten Codes innerhalb von TAF3 weiterverwenden, und wir exportieren dann aber den neuen LADV Code ins XML.

Wenn wir es nicht auflösen können, zeigen wir eine entsprechende Warnung, und überspringen diese Klasse beim export.

**Comment by mschunk** [comment]
Ok klingt gut.
